### ISSUE TITLE
optional<T&> converting constructor fails for assignment from empty

### ISSUE THREAD

**Issue by steve-downey** [beman-project/Optional26#49]
Bjorn Reese  writes:
Section [optional.ctor] has the following constructor:

   template <class U>
   constexpr explicit(see below) optional(const optional<U>& rhs);

I assume that this constructor is intended for interoperability with
regular optional<T>.

I have encountered several problems with the above.

First, we cannot create an mutable optional<T&> from optional<T> because
the constructor takes a const-ref and regular optional is not shallow
const.

   optional<int> object;
   optional<int&> ref(object); // Fails
   optional<const int&> cref(object); // Ok

Second, the effects states that "If rhs refers to a value, initializes
val with the value of addressof(rhs.value()))". This does not mention
what happens if rhs has no value. The reference implementation does not
handle this case either -- in fact, it points to an uninitialized value
yet reports that it has a value.

This design looks fragile and can lead to surprises for the normal user.
For example:

   optional<int> object(11); // Engage value
   optional<const int&> ref(object);
   object = nullopt; // Disengage value
   assert(ref); // Reports disengaged value as engaged

or...

   optional<int> object; // Disengage value
   optional<const int&> ref(object);
   object = 11; // Engage value
   assert(!ref); // Reports engaged value as disengaged

The normal user would probably expect the reference optional to report
the same as the regular optional.

Third, is the constraint in paragraph 14.1 redundant? It excludes
optional<optional<U>>.

Four, you may consider using to_address(rhs)) rather than
addressof(rhs.value()).

**Comment by steve-downey** [comment]
It occurs to me I can do slightly better in the optional<U>&& case if U is a reference type, as the value of the pointer is fine to borrow as long as it is convertible to a T*. Will need to overload on a constraint being true/false but that isn't terrible or novel.

**Comment by steve-downey** [comment]
Same fix applies to optional<T&>::optional(const optional<U>& rhs)

**Comment by breese** [comment]
After some practical experience I believe that it is prudent to restrict the constructor to take `optional<U&>` rather than `optional<U>`. While this means no direct interoperability with regular `optional<U>`, it is also less error-prone.

In other words, change

    template <class U>
    constexpr explicit(see below) optional(const optional<U>&);

into

    template <class U>
    constexpr optional(optional<U&>);

Notice that the explicit condition is no longer needed, and the argument is passed by value.

The purpose of this constructor is mutable-to-const and derived-to-base conversions.

Users can still reference regular optional values using `optional<T>::value()` which makes it clearer that it may entail dangling references.

    optional<int> object(11); // Engaged
    auto ref = optional<int&>(object.value());
    object = nullopt; // Disengaging... ref is dangling

or...

    optional<int> object; // Disengaged
    auto ref = optional<int&>(object.value()); // Throws bad_optional_access

If we want safer interoperability with regular optional where `optional<T&>::has_value()` always reflects `optional<T>::has_value()`, then `optional<T&>` must be extended with type-erasure which means it will no longer be zero-overhead.

**Comment by steve-downey** [comment]
```C++
    template <class U>
    constexpr optional& operator=(optional<U>&& rhs) = delete;
```
seems to take care of most of the problems. This means that we can't bind a prvalue returned from a function or one created directly. We can still bind the T& to a U for things that don't look like temporaries. There's still some risk here, but it seems to me the normal level of lifetime risk with references? 

```C++
    optional_base_const_ref = beman::optional26::optional<derived>(derived(3, 4));
    optional_base_const_ref = [](){return beman::optional26::optional<derived>(derived(3, 4));}();
```
are both rejected while
```C++
optional_base_const_ref = engaged_derived;
```

succeeds.

https://github.com/steve-downey/Optional26/blob/standard-normal-form/src/Beman/Optional26/tests/optional_ref.t.cpp#L617-L620 for tests, although I still need to work out good "fail-to-compile" tests.
