### ISSUE TITLE
Only non-const iterators for T&?

### ISSUE THREAD

**Issue by juxeii** [beman-project/optional26#65]
If I understand it correctly, the const strategy of `optional<T&>` is shallow, which means that the underlying pointer cannot change, only the pointee.
If this is correct than IMHO the iterators should only have "`const`" non-const `begin `and `end`.

```
constexpr iterator begin() const noexcept { return iterator(has_value() ? value_ : nullptr); };
constexpr iterator end() const noexcept { return begin() + has_value(); };
```

**Comment by frederick-vs-ja** [comment]
See [LWG3320](https://cplusplus.github.io/LWG/issue3320) and [P2278R4](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2278r4.html).
