### ISSUE TITLE
value_or for optional<T&> can return lvalue reference

### ISSUE THREAD

**Issue by juxeii** [beman-project/optional26#66]
Why do we always return a `T` in `value_or `for `optional<T&>`?
https://github.com/beman-project/optional26/blob/4c5cd80a337decdbeaaba26ee1b2b65359c8316c/include/beman/optional26/optional.hpp#L1117

If the provided default value is also a lvalue ref, can't we then safely return a `T&`?

**Comment by frederick-vs-ja** [comment]
This direction was vetoed in [P2988R4](https://wg21.link/p2988r4).

**Comment by juxeii** [comment]
Thanks for this hint. We have implemented our own optional type, but made the distinction when the provided value is a lvalue or not. So far we have no issues with this decission.
